/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.api;

import org.junit.Test;

/**
 * API tests for DefaultApi
 */

public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi( );


    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void authenticatedGetTest() {
        api.authenticatedGet( );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
   // @Test
    public void relationGraphGetTest() {
        String relationType = "Jobtech";
        String response = api.relationGraphGet( relationType );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void relationTypesGetTest() {
        String response = api.relationTypesGet( );

        // TODO: test validations
    }

}
