/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.api;

import org.junit.Ignore;
import org.junit.Test;
import se.jobtech.taxonomy.client.model.ERRORUNKNOWN;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi( );


    /**
     * @throws Exception if the Api call fails
     */
    @Test
    public void authenticatedGetTest() {
        api.authenticatedGet( );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void relationGraphRelationTypeGetTest() {
        String relationType = null;
        ERRORUNKNOWN response = api.relationGraphRelationTypeGet( relationType );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void relationGraphRelationTypeIdGetTest() {
        String relationType = null;
        String id = null;
        ERRORUNKNOWN response = api.relationGraphRelationTypeIdGet( relationType, id );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void relationTypesGetTest() {
        ERRORUNKNOWN response = api.relationTypesGet( );

        // TODO: test validations
    }

}
