/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 0.9.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.api;

import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for PrivateApi
 */
@Ignore
public class PrivateApiTest {

    private final PrivateApi api = new PrivateApi( );


    /**
     * Retract the concept with the given ID.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void v0TaxonomyPrivateConceptDeleteTest() {
        String id = null;
        api.v0TaxonomyPrivateConceptDelete( id );

        // TODO: test validations
    }

    /**
     * Assert a new concept.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void v0TaxonomyPrivateConceptPostTest() {
        String type = null;
        String description = null;
        String preferredTerm = null;
        api.v0TaxonomyPrivateConceptPost( type, description, preferredTerm );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void v0TaxonomyPrivateRelationGraphRelationTypeGetTest() {
        String relationType = null;
        ERRORUNKNOWN response = api.v0TaxonomyPrivateRelationGraphRelationTypeGet( relationType );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void v0TaxonomyPrivateRelationGraphRelationTypeIdGetTest() {
        String relationType = null;
        String id = null;
        ERRORUNKNOWN response = api.v0TaxonomyPrivateRelationGraphRelationTypeIdGet( relationType, id );

        // TODO: test validations
    }

    /**
     * Relation graphs.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void v0TaxonomyPrivateRelationTypesGetTest() {
        ERRORUNKNOWN response = api.v0TaxonomyPrivateRelationTypesGet( );

        // TODO: test validations
    }

    /**
     * Replace old concept with a new concept.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void v0TaxonomyPrivateReplaceConceptPostTest() {
        String oldConceptId = null;
        String newConceptId = null;
        api.v0TaxonomyPrivateReplaceConceptPost( oldConceptId, newConceptId );

        // TODO: test validations
    }

}
