/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PrivateApi
 */
@Ignore
public class PrivateApiTest {

    private final PrivateApi api = new PrivateApi();

    
    /**
     * Read all concepts of the given type.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxonomyPrivateApiConceptAllGetTest() {
        String type = null;
        api.taxonomyPrivateApiConceptAllGet(type);

        // TODO: test validations
    }
    
    /**
     * Retract the concept with the given ID.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxonomyPrivateApiConceptDeleteTest() {
        String id = null;
        api.taxonomyPrivateApiConceptDelete(id);

        // TODO: test validations
    }
    
    /**
     * Read a concept by ID.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxonomyPrivateApiConceptGetTest() {
        String id = null;
        api.taxonomyPrivateApiConceptGet(id);

        // TODO: test validations
    }
    
    /**
     * Assert a new concept.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxonomyPrivateApiConceptPostTest() {
        String type = null;
        String description = null;
        String preferredTerm = null;
        api.taxonomyPrivateApiConceptPost(type, description, preferredTerm);

        // TODO: test validations
    }
    
    /**
     * Read a list of all taxonomy types.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxonomyPrivateApiConceptTypesGetTest() {
        api.taxonomyPrivateApiConceptTypesGet();

        // TODO: test validations
    }
    
    /**
     * Replace old concept with a new concept.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxonomyPrivateApiReplaceConceptPostTest() {
        String oldConceptId = null;
        String newConceptId = null;
        api.taxonomyPrivateApiReplaceConceptPost(oldConceptId, newConceptId);

        // TODO: test validations
    }
    
}
