/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.api;

/**
 * API tests for PrivateApi
 */

public class PrivateApiTest {

    private final PrivateApi api = new PrivateApi( );


    /**
     * Retract the concept with the given ID.
     *
     * @throws Exception if the Api call fails
     */
    //@Test
    public void taxonomyPrivateConceptDeleteTest() {
        String id = null;
        api.taxonomyPrivateConceptDelete( id );

        // TODO: test validations
    }

    /**
     * Assert a new concept.
     *
     * @throws Exception if the Api call fails
     */
    // @Test
    public void taxonomyPrivateConceptPostTest() {
        String type = null;
        String description = null;
        String preferredTerm = null;
        api.taxonomyPrivateConceptPost( type, description, preferredTerm );

        // TODO: test validations
    }

    /**
     * Replace old concept with a new concept.
     *
     * @throws Exception if the Api call fails
     */
    // @Test
    public void taxonomyPrivateReplaceConceptPostTest() {
        String oldConceptId = null;
        String newConceptId = null;
        api.taxonomyPrivateReplaceConceptPost( oldConceptId, newConceptId );

        // TODO: test validations
    }

}
