/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.api;


import org.junit.Test;
import se.jobtech.taxonomy.client.model.Response38922;
import se.jobtech.taxonomy.client.model.Response38925;
import se.jobtech.taxonomy.client.model.Response38928;
import se.jobtech.taxonomy.client.model.Response38930;

import java.util.List;

/**
 * API tests for PublicApi
 */

public class PublicApiTest {

    private final PublicApi api = new PublicApi( );


    /**
     * Read all concepts of the given type.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void taxonomyPublicConceptAllGetTest() {
        String type = "driving-license";
        api.taxonomyPublicConceptAllGet( type );

        // TODO: test validations
    }

    /**
     * Read a concept by ID.
     *
     * @throws ApiException if the Api call fails
     *                      <p>
     *                      <p>
     *                      {
     *                      "category": "driving-license",
     *                      "transaction-id": 13194139533317,
     *                      "preferred-term": "D",
     *                      "timestamp": "2019-05-03T15:56:10Z",
     *                      "concept-id": "hK1a_wsQ_4UG",
     *                      "event-type": "CREATED"
     *                      }
     */
    @Test
    public void taxonomyPublicConceptGetTest() {
        String id = "hK1a_wsQ_4UG";
        api.taxonomyPublicConceptGet( id );

        // TODO: test validations
    }

    /**
     * Show the history since the given date. Use the format yyyy-MM-dd HH:mm:ss (i.e. 2017-06-09 14:30:01).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void taxonomyPublicConceptHistorySinceGetTest() {
        String dateTime = "2018-08-08 14:00:00";
        List<Response38930> response = api.taxonomyPublicConceptHistorySinceGet( dateTime );

        // TODO: test validations
    }

    /**
     * Read a list of all taxonomy types.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void taxonomyPublicConceptTypesGetTest() {
        api.taxonomyPublicConceptTypesGet( );

        System.out.println( "TESTING" );
    }

    /**
     * Show the history since the given date. Use the format yyyy-MM-dd HH:mm:ss (i.e. 2017-06-09 14:30:01).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void taxonomyPublicDeprecatedConceptHistorySinceGetTest() {
        String dateTime = "2018-08-08 14:00:00";
        String response = api.taxonomyPublicDeprecatedConceptHistorySinceGet( dateTime );

        // TODO: test validations
    }

    /**
     * Show the complete history.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void taxonomyPublicFullHistoryGetTest() {
        List<Response38928> response = api.taxonomyPublicFullHistoryGet( );


        // TODO: test validations
    }

    /**
     * Search for a term across all taxonomies.
     *
     * @throws ApiException if the Api call fails
     */
    // @Test
    public void taxonomyPublicTermGetTest() {
        String term = "Danska";
        List<Response38922> response = api.taxonomyPublicTermGet( term );

        // TODO: test validations
    }

    /**
     * get concepts by part of string
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void taxonomyPublicTermPartGetTest() {
        String term = "Danska";
        List<Response38925> response = api.taxonomyPublicTermPartGet( term );

        // TODO: test validations
    }

}
