/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Response38922
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-07T09:41:34.700+02:00")
public class Response38922 {
    @JsonProperty("id")
    private String id = null;

    @JsonProperty("definition")
    private String definition = null;

    @JsonProperty("instanceType")
    private String instanceType = null;

    @JsonProperty("deprecated")
    private Boolean deprecated = null;

    public Response38922 id( String id ) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public String getId() {
        return id;
    }

    public void setId( String id ) {
        this.id = id;
    }

    public Response38922 definition( String definition ) {
        this.definition = definition;
        return this;
    }

    /**
     * Get definition
     *
     * @return definition
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDefinition() {
        return definition;
    }

    public void setDefinition( String definition ) {
        this.definition = definition;
    }

    public Response38922 instanceType( String instanceType ) {
        this.instanceType = instanceType;
        return this;
    }

    /**
     * Get instanceType
     *
     * @return instanceType
     **/
    @ApiModelProperty(required = true, value = "")
    public String getInstanceType() {
        return instanceType;
    }

    public void setInstanceType( String instanceType ) {
        this.instanceType = instanceType;
    }

    public Response38922 deprecated( Boolean deprecated ) {
        this.deprecated = deprecated;
        return this;
    }

    /**
     * Get deprecated
     *
     * @return deprecated
     **/
    @ApiModelProperty(value = "")
    public Boolean isDeprecated() {
        return deprecated;
    }

    public void setDeprecated( Boolean deprecated ) {
        this.deprecated = deprecated;
    }


    @Override
    public boolean equals( java.lang.Object o ) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass( ) != o.getClass( )) {
            return false;
        }
        Response38922 response38922 = (Response38922) o;
        return Objects.equals( this.id, response38922.id ) &&
                Objects.equals( this.definition, response38922.definition ) &&
                Objects.equals( this.instanceType, response38922.instanceType ) &&
                Objects.equals( this.deprecated, response38922.deprecated );
    }

    @Override
    public int hashCode() {
        return Objects.hash( id, definition, instanceType, deprecated );
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder( );
        sb.append( "class Response38922 {\n" );

        sb.append( "    id: " ).append( toIndentedString( id ) ).append( "\n" );
        sb.append( "    definition: " ).append( toIndentedString( definition ) ).append( "\n" );
        sb.append( "    instanceType: " ).append( toIndentedString( instanceType ) ).append( "\n" );
        sb.append( "    deprecated: " ).append( toIndentedString( deprecated ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString( );
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o ) {
        if (o == null) {
            return "null";
        }
        return o.toString( ).replace( "\n", "\n    " );
    }

}

