/*
 * Jobtech Taxonomy
 * Jobtech taxonomy services
 *
 * OpenAPI spec version: 0.9.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.jobtech.taxonomy.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Response2996
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-24T11:20:52.800+02:00")
public class Response2996 {
    @JsonProperty("id")
    private String id = null;

    @JsonProperty("definition")
    private String definition = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("preferredLabel")
    private String preferredLabel = null;

    public Response2996 id( String id ) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public String getId() {
        return id;
    }

    public void setId( String id ) {
        this.id = id;
    }

    public Response2996 definition( String definition ) {
        this.definition = definition;
        return this;
    }

    /**
     * Get definition
     *
     * @return definition
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDefinition() {
        return definition;
    }

    public void setDefinition( String definition ) {
        this.definition = definition;
    }

    public Response2996 type( String type ) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @ApiModelProperty(required = true, value = "")
    public String getType() {
        return type;
    }

    public void setType( String type ) {
        this.type = type;
    }

    public Response2996 preferredLabel( String preferredLabel ) {
        this.preferredLabel = preferredLabel;
        return this;
    }

    /**
     * Get preferredLabel
     *
     * @return preferredLabel
     **/
    @ApiModelProperty(value = "")
    public String getPreferredLabel() {
        return preferredLabel;
    }

    public void setPreferredLabel( String preferredLabel ) {
        this.preferredLabel = preferredLabel;
    }


    @Override
    public boolean equals( java.lang.Object o ) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass( ) != o.getClass( )) {
            return false;
        }
        Response2996 response2996 = (Response2996) o;
        return Objects.equals( this.id, response2996.id ) &&
                Objects.equals( this.definition, response2996.definition ) &&
                Objects.equals( this.type, response2996.type ) &&
                Objects.equals( this.preferredLabel, response2996.preferredLabel );
    }

    @Override
    public int hashCode() {
        return Objects.hash( id, definition, type, preferredLabel );
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder( );
        sb.append( "class Response2996 {\n" );

        sb.append( "    id: " ).append( toIndentedString( id ) ).append( "\n" );
        sb.append( "    definition: " ).append( toIndentedString( definition ) ).append( "\n" );
        sb.append( "    type: " ).append( toIndentedString( type ) ).append( "\n" );
        sb.append( "    preferredLabel: " ).append( toIndentedString( preferredLabel ) ).append( "\n" );
        sb.append( "}" );
        return sb.toString( );
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( java.lang.Object o ) {
        if (o == null) {
            return "null";
        }
        return o.toString( ).replace( "\n", "\n    " );
    }

}

